name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
    - uses: actions/checkout@v3
    - name: Build and Push the Backend1 image
      run: |
        cd backend1
        docker build . --file Dockerfile --tag backend1:$(date +%s)
        docker push ghcr.io/swingyman/backend1:latest
    - name: Build and Push the Backend2 image
      run: |
        cd backend2
        docker build . --file Dockerfile --tag backend2:$(date +%s)
        docker push ghcr.io/swingyman/backend2:latest
    - name: Build and Push the Frontend image
      run: |
        cd frontend
        docker build . --file Dockerfile --tag frontend:$(date +%s)
        docker push ghcr.io/swingyman/frontend:latest
    - name: Build and Push the Loadbalancer image
      run: |
        cd loadbalancer
        docker build . --file Dockerfile --tag loadbalancer:$(date +%s)
        docker push ghcr.io/swingyman/loadbalancer:latest

