name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file /backend1/Dockerfile --tag backend1:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file /backend2/Dockerfile --tag backend2:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file /frontend/Dockerfile --tag frontend:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file /loadbalancer/Dockerfile --tag loadbalancer:$(date +%s)

