name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd backend1
        docker build . --file Dockerfile --tag backend1:$(date +%s)
        docker push ghcr.io/swingyman/backend1:latest
    - name: Build the Docker image
      run: |
        cd backend2
        docker build . --file Dockerfile --tag backend2:$(date +%s)
        docker push ghcr.io/swingyman/backend2:latest
    - name: Build the Docker image
      run: |
        cd frontend
        docker build . --file Dockerfile --tag frontend:$(date +%s)
        docker push ghcr.io/swingyman/frontend:latest
    - name: Build the Docker image
      run: |
        cd loadbalancer
        docker build . --file Dockerfile --tag loadbalancer:$(date +%s)
        docker push ghcr.io/swingyman/loadbalancer:latest

