name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
    -
      name: Build and Push the Backend1 image
      uses: docker/build-push-action@v4
      with:
          push: true
          tags: ghcr.io/swingyman/backend1:latest
          context: ./backend1/.
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.TOKEN }}
    - name: Build and Push the Backend2 image
      uses: docker/build-push-action@v4
      with:
          push: true
          tags: ghcr.io/swingyman/backend2:latest
          context: ./backend2/.
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.TOKEN }}
    - name: Build and Push the Frontend image
      uses: docker/build-push-action@v4
      with:
          push: true
          tags: ghcr.io/swingyman/frontend:latest
          context: ./frontend/.
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.TOKEN }}
    - name: Build and Push the Loadbalancer image
      uses: docker/build-push-action@v4
      with:
          push: true
          tags: ghcr.io/swingyman/loadbalancer:latest
          context: ./loadbalancer/.
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.TOKEN }}
