name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
    - uses: actions/checkout@v3
    -
      name: Build and Push the Backend1 image
      uses: docker/build-push-action@v4
      with:
          push: true
          tags: swingyman/backend1:latest
          context: /backend1
    - name: Build and Push the Backend2 image
      uses: docker/build-push-action@v4
      with:
          push: true
          tags: swingyman/backend2:latest
          context: /backend2
    - name: Build and Push the Frontend image
      uses: docker/build-push-action@v4
      with:
          push: true
          tags: swingyman/frontend:latest
          context: /frontend
    - name: Build and Push the Loadbalancer image
      uses: docker/build-push-action@v4
      with:
          push: true
          tags: swingyman/loadbalancer:latest
          context: /loadbalancer
